AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable


Style/Documentation:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - './spree-seo.gemspec'

Lint/MissingSuper:
  Exclude:
    - 'app/**/*'

Metrics/MethodLength:
  Exclude:
    - app/controllers/spree/admin/taxon_filter_combinations_controller.rb
