require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  FailLevel: error

Style/Documentation:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - './spree-seo.gemspec'

Lint/MissingSuper:
  Exclude:
    - 'app/**/*'
